[auth]
site_url = "http://localhost:8080"

additional_redirect_urls = [
  "http://localhost:8080/auth?type=recovery"
]

# Delete / comment these:
# [auth.email]
#
# [auth.email.smtp]
# enabled = true
# host = "mailpit"
# port = 1025
# user = ""
# pass = ""
# admin_email = "no-reply@localhost"
# sender_name = "ReelyRated (Local Dev)"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000